### ISSUE TITLE
Sparkhello: Error in spark_compile(jar_name = jar_name, spark_home = spark_home, scalac = scalac_path,  :    failed to discover Spark jars

### ISSUE THREAD

**Issue by Vonisoa** [javierluraschi/sparkhello#3]
Hello, sorry to disturb you!
I tried sparkhello on windows but when I run
 `sparklyr::compile_package_jars()`
It ask me to specify spark version and when I specify it(2.1.0), I got error like this:

==> using scalac 2.11.7
==> building against Spark 2.1.0
==> building 'sparkhello-1.5-2.10.jar' ...
Error in spark_compile(jar_name = jar_name, spark_home = spark_home, scalac = scalac_path,  : 
  failed to discover Spark jars
Can you help me please?

**Comment by javierluraschi** [comment]
@Vonisoa this is probably caused by missing `scalac` versions, `sparklyr` needs `2.10` and `2.11`. You could either, manually download them into `Documents/scala` but I would rather recommend to run `download_scalac()` which is available in the latest version of `sparklyr`, once this function is run, it will install the required `scalac` compilers.

**Comment by Vonisoa** [comment]
OK Thank you, let's try this and I will tell if if it solve the issue!

**Comment by javierluraschi** [comment]
Let us know if it doesn't! Thanks for giving this a shot. Cheers.
